[unstable]
#  the compiler_builtins crate already contains implementations for all the needed functions,
# they are just disabled by default to not collide with the implementations from the C library.
# https://github.com/rust-lang/compiler-builtins/blob/eff506cd49b637f1ab5931625a33cef7e91fbbf6/src/mem.rs#L12-L69
# https://doc.rust-lang.org/cargo/reference/config.html
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-rust_os.json"

# qemu-system-x86_64 -drive format=raw,file=target/x86_64-rust_os/debug/bootimage-rust-os.bin 
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
